
export const builtinList = [
	"set_key_of",
	"unify",
	"unify_left",
	"unify_right",
	"unify_equal",
	"unify_not_equal",
	"slice",
	"length",
	"list",
	"first",
	"rest",
	"empty",
	"add",
	"subtract",
	"multiply",
	"divide",
	"modulo",
	"negate",
	"internal_file",
	"internal_import",
	"cons",
	"internal_append",
	"string_to_list",
] as const;
export const builtinsByRecursiveness: Record<Builtin, number> = {
	set_key_of: 0,
	unify: 0,
	unify_left: 0,
	unify_right: 0,
	unify_equal: 0,
	unify_not_equal: 0,
	slice: 0,
	length: 0,
	list: 0,
	first: 0,
	rest: 0,
	empty: 0,
	add: 0,
	subtract: 0,
	multiply: 0,
	divide: 0,
	modulo: 0,
	negate: 0,
	internal_file: 0,
	internal_import: 0,
	string_to_list: 1,
	cons: 1,
	internal_append: 3,
};

export type Builtin = (typeof builtinList)[number];
